DROP TABLE MEMBERS;

SELECT * FROM MEMBERS;

CREATE TABLE MEMBERS (
	M_ID	VARCHAR2(30),
	M_PW	VARCHAR2(30)		NOT NULL,
	M_NAME	VARCHAR2(20)    NOT NULL,
	M_BIRTH	DATE            DEFAULT SYSDATE,
	M_PHONE	VARCHAR2(30)    ,
	M_EMAIL	VARCHAR2(50)    ,
	M_ADDRESS	VARCHAR2(50)	NOT NULL,
	M_GRADE	VARCHAR2(20)	NOT NULL,
    
    CONSTRAINT MEMBER_ID_PK PRIMARY KEY(M_ID),
    CONSTRAINT MEMBER_PHONE_UK UNIQUE(M_PHONE),
    CONSTRAINT MEMBER_EMAIL_UK UNIQUE(M_EMAIL)       
);

DROP TABLE MEMBER_REGISTER;

CREATE TABLE MEMBER_REGISTER (
	M_ID	VARCHAR2(20)		,
	M_ID2	VARCHAR2(30)	    NOT NULL, --식별관계
	M_PW	VARCHAR2(40)		NOT  NULL,
	M_NAME	VARCHAR2(20)	NOT	NULL,
	M_ADDRESS	VARCHAR2(100)	NOT	NULL,
	M_PHONE	VARCHAR2(20)	,
    M_EMAIL	VARCHAR2(100)	,
    
    CONSTRAINT MEMBER_REGISTER_ID_PK PRIMARY KEY(M_ID),
    CONSTRAINT MEBMER_REGISTER_PHONE_UK UNIQUE (M_PHONE),
    CONSTRAINT MEMBER_REGISTER_EMAIL_UK UNIQUE (M_EMAIL),
    CONSTRAINT M_ID2_FK FOREIGN KEY(M_ID2) REFERENCES MEMBERS(M_ID)
);

DROP TABLE ORDERS;

CREATE TABLE ORDERS (
	ORDERNUMBER VARCHAR2(30),
	ORDERDATE	DATE		    DEFAULT SYSDATE,
	BOOKNAME	VARCHAR2(50),
	PRICE	NUMBER(6)		    NOT NULL,
	B_COUNT	NUMBER(3)       DEFAULT 0,
	B_SUM	NUMBER(10)		    DEFAULT 0,
	ADDERESS	VARCHAR2(30)	NOT	NULL,
    
    CONSTRAINT ORDER_ORDERNUMBER_PK PRIMARY KEY(ORDERNUMBER),
    CONSTRAINT ORDER_BOOKNAME_UK UNIQUE(BOOKNAME)      
);

DROP TABLE BOOK_INFO;

CREATE TABLE BOOK_INFO (
	BOOK_ID	NUMBER(10),
	BOOK_NAME	VARCHAR2(100),
	BOOK_PRICE	VARCHAR2(40) DEFAULT 0,
	BOOK_WRITER	VARCHAR2(40)	NOT NULL,
	BOOK_DISCOUNT	NUMBER(3)		,
	BOOK_CATEGORY	VARCHAR2(40)	NOT NULL,
	BOOK_COUNT	NUMBER(3)		DEFAULT 0,
    
    CONSTRAINT BOOK_INFO_BOOK_ID PRIMARY KEY(BOOK_ID),
    CONSTRAINT BOOK_INFO_BOOK_NAME_UK UNIQUE(BOOK_NAME),
    CONSTRAINT BOOK_INFO_BOOK_DISCOUNT_CK CHECK(BOOK_DISCOUNT>0)   
);

DROP TABLE CART;

CREATE TABLE CART (
	CART_ID	NUMBER(38),
	P_NAME	VARCHAR2(30),
	P_COUNT	NUMBER(10)		DEFAULT 0,
	M_ID	VARCHAR2(30), --비식별
	BOOK_ID	NUMBER(10), --비식별
	ORDERNUMBER	VARCHAR2(30), --비식별
    
    CONSTRAINT CART_CART_ID PRIMARY KEY(CART_ID),
    CONSTRAINT CART_P_NAME_UK UNIQUE(P_NAME),
    CONSTRAINT CART_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBERS(M_ID),
    CONSTRAINT CART_BOOK_ID_FK FOREIGN KEY(BOOK_ID) REFERENCES BOOK_INFO(BOOK_ID),
    CONSTRAINT CART_ORDERNUMBER_FK FOREIGN KEY(ORDERNUMBER) REFERENCES ORDERS(ORDERNUMBER)   
);

DROP TABLE P_IMAGE;

CREATE TABLE P_IMAGE (
	I_NO	NUMBER(10),
	I_PATH	VARCHAR2(30)	NOT NULL,
	BOOK_ID	NUMBER(10), --비식별
    
    CONSTRAINT P_IMAGE_I_NO_PK PRIMARY KEY(I_NO),
    CONSTRAINT P_IMAGE_BOOK_ID_FK FOREIGN KEY(BOOK_ID) REFERENCES BOOK_INFO(BOOK_ID)
);

DROP TABLE ORDER_LIST;

CREATE TABLE ORDER_LIST (
	ORDERNUMBER	VARCHAR2(30)    NOT NULL, --식별
	BOOK_ID	NUMBER(10)		    NOT NULL, --식별
	P_COUNT	NUMBER(10)		    DEFAULT 0,
	P_S_PRICE	NUMBER(20)		    DEFAULT 0,
	ORDER_STATE	VARCHAR2(20)	NOT	NULL,
    
    CONSTRAINT ORDER_LIST_ORDERNUMBER_FK FOREIGN KEY(ORDERNUMBER) REFERENCES ORDERS(ORDERNUMBER),
    CONSTRAINT ORDER_LIST_BOOK_ID_FK FOREIGN KEY(BOOK_ID) REFERENCES BOOK_INFO(BOOK_ID)
);

DROP TABLE ADDERESS;

CREATE TABLE ADDERESS (
	ORDERNUMBER	VARCHAR2(30)	NOT NULL, --식별
	M_ID	VARCHAR2(30), --비식별
    
    CONSTRAINT ADDERESS_ORDERNUMBER_FK FOREIGN KEY(ORDERNUMBER) REFERENCES ORDERS(ORDERNUMBER),
    CONSTRAINT ADDERESS_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBERS(M_ID)
);

DROP TABLE REVIEW;

CREATE TABLE REVIEW (
	R_ID	VARCHAR2(30), 
	R_INFO	VARCHAR2(1000),
	M_ID	VARCHAR2(30), --비식별
    
    CONSTRAINT REVIEW_ID_PK PRIMARY KEY(R_ID),
    CONSTRAINT REVIEW_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBERS(M_ID)
);

DROP TABLE PAYMENT;

CREATE TABLE PAYMENT (
	PAY	VARCHAR2(40)		PRIMARY KEY,
	ORDERNUMBER	VARCHAR2(30)	NOT NULL, --식별
    
    CONSTRAINT PAYMENT_PAY_PK PRIMARY KEY(PAYMENT),
    CONSTRAINT PAYMENT_ORDERNUMBER_FK FOREIGN KEY(ORDERNUMBER) REFERENCES ORDERS(ORDERNUMBER)
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"M_ID"
);

ALTER TABLE "MEMBER_REGISTER" ADD CONSTRAINT "PK_MEMBER_REGISTER" PRIMARY KEY (
	"M_ID",
	"M_ID2"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDERNUMBER"
);

ALTER TABLE "BOOK_INFO" ADD CONSTRAINT "PK_BOOK_INFO" PRIMARY KEY (
	"BOOK_ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_ID"
);

ALTER TABLE "P_IMAGE" ADD CONSTRAINT "PK_P_IMAGE" PRIMARY KEY (
	"I_NO"
);

ALTER TABLE "ORDER_LIST" ADD CONSTRAINT "PK_ORDER_LIST" PRIMARY KEY (
	"ORDERNUMBER",
	"BOOK_ID"
);

ALTER TABLE "ADDERESS" ADD CONSTRAINT "PK_ADDERESS" PRIMARY KEY (
	"ORDERNUMBER"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"ID"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT",
	"ORDERNUMBER"
);

ALTER TABLE "MEMBER_REGISTER" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_REGISTER_1" FOREIGN KEY (
	"M_ID2"
)
REFERENCES "MEMBER" (
	"M_ID"
);

ALTER TABLE "ORDER_LIST" ADD CONSTRAINT "FK_ORDER_TO_ORDER_LIST_1" FOREIGN KEY (
	"ORDERNUMBER"
)
REFERENCES "ORDER" (
	"ORDERNUMBER"
);

ALTER TABLE "ORDER_LIST" ADD CONSTRAINT "FK_BOOK_INFO_TO_ORDER_LIST_1" FOREIGN KEY (
	"BOOK_ID"
)
REFERENCES "BOOK_INFO" (
	"BOOK_ID"
);

ALTER TABLE "ADDERESS" ADD CONSTRAINT "FK_ORDER_TO_ADDERESS_1" FOREIGN KEY (
	"ORDERNUMBER"
)
REFERENCES "ORDER" (
	"ORDERNUMBER"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_ORDER_TO_PAYMENT_1" FOREIGN KEY (
	"ORDERNUMBER"
)
REFERENCES "ORDER" (
	"ORDERNUMBER"
);

